apiVersion: apps/v1
kind: Deployment
metadata:
  name: gizmo-help-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: gizmo-help
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gizmo-help
    spec:
      containers:
      - name: gizmo-help-container
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: gizmo-help-svc
  labels:
    app: gizmo-help
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: gizmo-help
